dist: trusty
language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g mocha@2.5.1
  - npm install -g eslint@0.18.0
  - curl 'https://raw.githubusercontent.com/xdv/javascript-style-guide/master/eslintrc' > ./eslintrc
  - eslint --reset -c ./eslintrc $(git --no-pager diff --name-only --diff-filter=AM --relative $(git merge-base FETCH_HEAD origin/HEAD) FETCH_HEAD | grep "\.js$")
script: MOCHA_REPORTER=tap npm test --coverage
after_success:
- npm run coveralls
notifications:
  email: false
  slack:
    rooms:
    - kedia:yBh1h5UbplmejFa7vTou1MD0#xdv
